spring.datasource.url=jdbc:postgresql://localhost:5432/spotydesk_db
spring.datasource.username=postgres
spring.datasource.password=alejoPendejo01
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
